# sudo /usr/libexec/docker/cli-plugins/docker-compose up -d
# sudo /usr/libexec/docker/cli-plugins/docker-compose stop
# sudo docker exec -it <container> /bin/bash

version: "3"
services:
  ccapi:
    stdin_open: true
    tty: true
    image: ccapi:v0.1
    container_name: ccapi
    environment:
      - TZ=Asia/Shanghai # Your current timezone
      - PUID=1000 # User id
      - PGID=1000 # Group id
    #volumes:
    #  - /mnt/shared/container/transmission/config:/config
    #command: ["/apps/ccapi"]
    ports:
      - 8083:8080 # Web UI port
    #restart: unless-stopped # This makes sure that the application restarts when it crashes
