# sudo docker compose up -d
# sudo docker compose stop
# sudo docker exec -it <container> /bin/bash

services:
  ccapi:
    stdin_open: true
    tty: true
    image: ccapi:v0.1
    container_name: ccapi
    environment:
      - TZ=Asia/Shanghai # Your current timezone
      - PUID=1000 # User id
      - PGID=1000 # Group id
    ports:
      - 80:5003 # Web UI port
    restart: unless-stopped # This makes sure that the application restarts when it crashes
